Vagrant.configure("2") do |config|
  # basic VM configuration
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.name = "Mininet-VM_RTman"
    v.memory = 1024
    v.cpus = 2
  end

  # network settings
  config.vm.network "private_network", ip: "192.168.33.3"

  # provision scripts
  config.vm.provision :shell, path: "provision.sh"
end
